---
- name: This is the setup script for lab 6.1
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    - user: Luigi
  
  tasks:
    - name: Creates user for lab
      user:
        name: "{{ user }}"

    - name: This creates a copy of the sudoers file
      ansible.builtin.copy:
        src: /etc/sudoers
        dest: /root/.sudoerscopy
        remote_src: yes
        validate: /usr/sbin/visudo -csf %s

    
